# Use an official Node.js image as a base image
FROM node:14

# Set the working directory inside the container
WORKDIR /react-app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire project to the working directory
COPY . .

# Build the React app
RUN npm run build

# Expose the port your app will run on
EXPOSE 81

# Define the command to run your app
CMD ["npm", "start"]

~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
