export const EVENTS_POST_REQUEST = "EVENTS_POST_REQUEST";
export const EVENTS_POST_SUCCESS = "EVENTS_POST_SUCCESS";
export const EVENTS_POST_FAIL = "EVENTS_POST_FAIL";

export const EVENTS_LIST_REQUEST = "EVENTS_LIST_REQUEST";
export const EVENTS_LIST_SUCCESS = "EVENTS_LIST_SUCCESS";
export const EVENTS_LIST_FAIL = "EVENTS_LIST_FAIL";

export const EVENTS_DELETE_REQUEST = "EVENTS_DELETE_REQUEST";
export const EVENTS_DELETE_SUCCESS = "EVENTS_DELETE_SUCCESS";
export const EVENTS_DELETE_FAIL = "EVENTS_DELETE_FAIL";

export const MEMORIAL_FLOWER_POST_REQUEST = "MEMORIAL_FLOWER_POST_REQUEST";
export const MEMORIAL_FLOWER_POST_SUCCESS = "MEMORIAL_FLOWER_POST_SUCCESS";
export const MEMORIAL_FLOWER_POST_FAIL = "MEMORIAL_FLOWER_POST_FAIL";

export const MEMORIAL_FLOWER_LIST_REQUEST = "MEMORIAL_FLOWER_LIST_REQUEST";
export const MEMORIAL_FLOWER_LIST_SUCCESS = "MEMORIAL_FLOWER_LIST_SUCCESS";
export const MEMORIAL_FLOWER_LIST_FAIL = "MEMORIAL_FLOWER_LIST_FAIL";

export const PROPERTY_POST_REQUEST = "PROPERTY_POST_REQUEST";
export const PROPERTY_POST_SUCCESS = "PROPERTY_POST_SUCCESS";
export const PROPERTY_POST_FAIL = "PROPERTY_POST_FAIL";

export const FAMILY_DETAIL_POST_REQUEST = "FAMILY_DETAIL_POST_REQUEST";
export const FAMILY_DETAIL_POST_SUCCESS = "FAMILY_DETAIL_POST_SUCCESS";
export const FAMILY_DETAIL_POST_FAIL = "FAMILY_DETAIL_POST_FAIL";

export const FAMILY_DETAIL_LIST_REQUEST = "FAMILY_DETAIL_LIST_REQUEST";
export const FAMILY_DETAIL_LIST_SUCCESS = "FAMILY_DETAIL_LIST_SUCCESS";
export const FAMILY_DETAIL_LIST_FAIL = "FAMILY_DETAIL_LIST_FAIL";

export const MEMORIAL_PERSON_DETAIL_POST_REQUEST =
  "MEMORIAL_PERSON_DETAIL_POST_REQUEST";
export const MEMORIAL_PERSON_DETAIL_POST_SUCCESS =
  "MEMORIAL_PERSON_DETAIL_POST_SUCCESS";
export const MEMORIAL_PERSON_DETAIL_POST_FAIL =
  "MEMORIAL_PERSON_DETAIL_POST_FAIL";



  export const EVENT_DETAILS_SHOW_BYID_REQUEST = "EVENT_DETAILS_SHOW_BYID_REQUEST";
export const EVENT_DETAILS_SHOW_BYID_SUCCESS = "EVENT_DETAILS_SHOW_BYID_SUCCESS";
export const EVENT_DETAILS_SHOW_BYID_FAIL = "EVENT_DETAILS_SHOW_BYID_FAIL";


export const EVENT_CATEGORYADD_REQUEST = "EVENT_CATEGORYADD_REQUEST";
export const EVENT_CATEGORYADD_SUCCESS = "EVENT_CATEGORYADD_SUCCESS";
export const EVENT_CATEGORYADD_FAIL = "EVENT_CATEGORYADD_FAIL";




