export const LEGACY_DOCUMENT_ADD_REQUEST = "LEGACY_DOCUMENT_ADD_REQUEST";
export const LEGACY_DOCUMENT_ADD_SUCCESS = "LEGACY_DOCUMENT_ADD_SUCCESS";
export const LEGACY_DOCUMENT_ADD_FAIL = "LEGACY_DOCUMENT_ADD_FAIL";

export const LEGACY_DOCUMENT_SHOW_LIST_REQUEST =
  "LEGACY_DOCUMENT_SHOW_LIST_REQUEST";
export const LEGACY_DOCUMENT_SHOW_LIST_SUCCESS =
  "LEGACY_DOCUMENT_SHOW_LIST_SUCCESS";
export const LEGACY_DOCUMENT_SHOW_LIST_FAIL = "LEGACY_DOCUMENT_SHOW_LIST_FAIL";

export const LEGACY_DOCUMENT_LIST_DELETE_REQUEST =
  "LEGACY_DOCUMENT_LIST_DELETE_REQUEST";
export const LEGACY_DOCUMENT_LIST_DELETE_SUCCESS =
  "LEGACY_DOCUMENT_LIST_DELETE_SUCCESS";
export const LEGACY_DOCUMENT_LIST_DELETE_FAIL =
  "LEGACY_DOCUMENT_LIST_DELETE_FAIL";

export const LEGACY_DOCUMENT_UPDATE_REQUEST = "LEGACY_DOCUMENT_UPDATE_REQUEST";
export const LEGACY_DOCUMENT_UPDATE_SUCCESS = "LEGACY_DOCUMENT_UPDATE_SUCCESS";
export const LEGACY_DOCUMENT_UPDATE_FAIL = "LEGACY_DOCUMENT_UPDATE_FAIL";

export const LEGACY_DOCUMENT_GET_DETAIL_BYID_REQUEST =
  "LEGACY_DOCUMENT_GET_DETAIL_BYID_REQUEST";
export const LEGACY_DOCUMENT_GET_DETAIL_BYID_SUCCESS =
  "LEGACY_DOCUMENT_GET_DETAIL_BYID_SUCCESS";
export const LEGACY_DOCUMENT_GET_DETAIL_BYID_FAIL =
  "LEGACY_DOCUMENT_GET_DETAIL_BYID_FAIL";

export const FAMILY_TODO_ADD_REQUEST = "FAMILY_TODO_ADD_REQUEST";
export const FAMILY_TODO_ADD_SUCCESS = "FAMILY_TODO_ADD_SUCCESS";
export const FAMILY_TODO_ADD_FAIL = "FAMILY_TODO_ADD_FAIL";

export const FAMILY_TODO_LIST_SHOW_REQUEST = "FAMILY_TODO_LIST_SHOW_REQUEST";
export const FAMILY_TODO_LIST_SHOW_SUCCESS = "FAMILY_TODO_LIST_SHOW_SUCCESS";
export const FAMILY_TODO_LIST_SHOW_FAIL = "FAMILY_TODO_LIST_SHOW_FAIL";

export const FAMILY_TODO_LIST_GET_BYID_REQUEST =
  "FAMILY_TODO_LIST_GET_BYID_REQUEST";
export const FAMILY_TODO_LIST_GET_BYID_SUCCESS =
  "FAMILY_TODO_LIST_GET_BYID_SUCCESS";
export const FAMILY_TODO_LIST_GET_BYID_FAIL = "FAMILY_TODO_LIST_GET_BYID_FAIL";

export const FAMILY_TODO_DELETE_LIST_REQUEST =
  "FAMILY_TODO_DELETE_LIST_REQUEST";
export const FAMILY_TODO_DELETE_LIST_SUCCESS =
  "FAMILY_TODO_DELETE_LIST_SUCCESS";
export const FAMILY_TODO_DELETE_LIST_FAIL = "FAMILY_TODO_DELETE_LIST_FAIL";

export const FAMILY_TODO_LIST_UPDATE_REQUEST =
  "FAMILY_TODO_LIST_UPDATE_REQUEST";
export const FAMILY_TODO_LIST_UPDATE_SUCCESS =
  "FAMILY_TODO_LIST_UPDATE_SUCCESS";
export const FAMILY_TODO_LIST_UPDATE_FAIL = "FAMILY_TODO_LIST_UPDATE_FAIL";

export const LAGACY_CODE_ENTER_PAGE_REQUEST = "LAGACY_CODE_ENTER_PAGE_REQUEST";
export const LAGACY_CODE_ENTER_PAGE_SUCCESS = "LAGACY_CODE_ENTER_PAGE_SUCCESS";
export const LAGACY_CODE_ENTER_PAGE_FAIL = "LAGACY_CODE_ENTER_PAGE_FAIL";

export const PASSWORD_ENTER_VERFICATION_REQUEST =
  "PASSWORD_ENTER_VERFICATION_REQUEST";
export const PASSWORD_ENTER_VERFICATION_SUCCESS =
  "PASSWORD_ENTER_VERFICATION_SUCCESS";
export const PASSWORD_ENTER_VERFICATION_FAIL =
  "PASSWORD_ENTER_VERFICATION_FAIL";

export const OTP_VERFICATION_REQUEST = "OTP_VERFICATION_REQUEST";
export const OTP_VERFICATION_SUCCESS = "OTP_VERFICATION_SUCCESS";
export const OTP_VERFICATION_FAIL = "OTP_VERFICATION_FAIL";

export const MEMORAIL_INFORMATION_RELATION_REQUEST =
  "MEMORAIL_INFORMATION_RELATION_REQUEST";
export const MEMORAIL_INFORMATION_RELATION_SUCCESS =
  "MEMORAIL_INFORMATION_RELATION_SUCCESS";
export const MEMORAIL_INFORMATION_RELATION_FAIL =
  "MEMORAIL_INFORMATION_RELATION_FAIL";

export const LEGACY_DATA_SHOW_MEMBER_REQUEST =
  "LEGACY_DATA_SHOW_MEMBER_REQUEST";
export const LEGACY_DATA_SHOW_MEMBER_SUCCESS =
  "LEGACY_DATA_SHOW_MEMBER_SUCCESS";
export const LEGACY_DATA_SHOW_MEMBER_FAIL = "LEGACY_DATA_SHOW_MEMBER_FAIL";

export const MEMBER_RELATION_LIST_REQUEST = "MEMBER_RELATION_LIST_REQUEST";
export const MEMBER_RELATION_LIST_SUCCESS = "MEMBER_RELATION_LIST_SUCCESS";
export const MEMBER_RELATION_LIST_FAIL = "MEMBER_RELATION_LIST_FAIL";

export const MEMBER_PERMISSION_GRANT_REQUEST =
  "MEMBER_PERMISSION_GRANT_REQUEST";
export const MEMBER_PERMISSION_GRANT_SUCCESS =
  "MEMBER_PERMISSION_GRANT_SUCCESS";
export const MEMBER_PERMISSION_GRANT_FAIL = "MEMBER_PERMISSION_GRANT_FAIL";

export const MEMBER_GIVE_PERMISSION_LEGACYSEE_REQUEST =
  "MEMBER_GIVE_PERMISSION_LEGACYSEE_REQUEST";
export const MEMBER_GIVE_PERMISSION_LEGACYSEE_SUCCESS =
  "MEMBER_GIVE_PERMISSION_LEGACYSEE_SUCCESS";
export const MEMBER_GIVE_PERMISSION_LEGACYSEE_FAIL =
  "MEMBER_GIVE_PERMISSION_LEGACYSEE_FAIL";

export const GET_PERMISSIONS_LIST_REQUEST = "GET_PERMISSIONS_LIST_REQUEST";
export const GET_PERMISSIONS_LIST_SUCCESS = "GET_PERMISSIONS_LIST_SUCCESS";
export const GET_PERMISSIONS_LIST_FAIL = "GET_PERMISSIONS_LIST_FAIL";

export const PERMISSIONS_DELETE_REQUEST = "PERMISSIONS_DELETE_REQUEST";
export const PERMISSIONS_DELETE_SUCCESS = "PERMISSIONS_DELETE_SUCCESS";
export const PERMISSIONS_DELETE_FAIL = "PERMISSIONS_DELETE_FAIL";

export const LEGACY_ALL_MODEL_DELETE_REQUEST =
  "LEGACY_ALL_MODEL_DELETE_REQUEST";
export const LEGACY_ALL_MODEL_DELETE_SUCCESS =
  "LEGACY_ALL_MODEL_DELETE_SUCCESS";
export const LEGACY_ALL_MODEL_DELETE_FAIL = "LEGACY_ALL_MODEL_DELETE_FAIL";

export const LEGACY_DELELTE_MODAL_ONE_BY_ONE_REQUEST =
  "LEGACY_DELELTE_MODAL_ONE_BY_ONE_REQUEST";
export const LEGACY_DELELTE_MODAL_ONE_BY_ONE_SUCCESS =
  "LEGACY_DELELTE_MODAL_ONE_BY_ONE_SUCCESS";
export const LEGACY_DELELTE_MODAL_ONE_BY_ONE_FAIL =
  "LEGACY_DELELTE_MODAL_ONE_BY_ONE_FAIL";

export const UPDATE_LAGACY_PASSWORD_REQUEST = "UPDATE_LAGACY_PASSWORD_REQUEST";
export const UPDATE_LAGACY_PASSWORD_SUCCESS = "UPDATE_LAGACY_PASSWORD_SUCCESS";
export const UPDATE_LAGACY_PASSWORD_FAIL = "UPDATE_LAGACY_PASSWORD_FAIL";

export const FORGOT_LEGACY_PASSWORD_REQUEST = "FORGOT_LEGACY_PASSWORD_REQUEST";
export const FORGOT_LEGACY_PASSWORD_SUCCESS = "FORGOT_LEGACY_PASSWORD_SUCCESS";
export const FORGOT_LEGACY_PASSWORD_FAIL = "FORGOT_LEGACY_PASSWORD_FAIL";

export const RESET_LEGACY_PASSWORD_REQUEST = "RESET_LEGACY_PASSWORD_REQUEST";
export const RESET_LEGACY_PASSWORD_SUCCESS = "RESET_LEGACY_PASSWORD_SUCCESS";
export const RESET_LEGACY_PASSWORD_FAIL = "RESET_LEGACY_PASSWORD_FAIL";

export const SALE_PEOPERTY_POST_REQUEST = "SALE_PEOPERTY_POST_REQUEST";
export const SALE_PEOPERTY_POST_SUCCESS = "SALE_PEOPERTY_POST_SUCCESS";
export const SALE_PEOPERTY_POST_FAIL = "SALE_PEOPERTY_POST_FAIL";

export const SALE_PEOPERTY_LIST_GET_REQUEST = "SALE_PEOPERTY_LIST_GET_REQUEST";
export const SALE_PEOPERTY_LIST_GET_SUCCESS = "SALE_PEOPERTY_LIST_GET_SUCCESS";
export const SALE_PEOPERTY_LIST_GET_FAIL = "SALE_PEOPERTY_LIST_GET_FAIL";

export const SALE_PROPERTY_DELETE_REQUEST = "SALE_PROPERTY_DELETE_REQUEST";
export const SALE_PROPERTY_DELETE_SUCCESS = "SALE_PROPERTY_DELETE_SUCCESS";
export const SALE_PROPERTY_DELETE_FAIL = "SALE_PROPERTY_DELETE_FAIL";

export const EDIT_PROPERTY_DATA_REQUEST = "EDIT_PROPERTY_DATA_REQUEST";
export const EDIT_PROPERTY_DATA_SUCCESS = "EDIT_PROPERTY_DATA_SUCCESS";
export const EDIT_PROPERTY_DATA_FAIL = "EDIT_PROPERTY_DATA_FAIL";

export const GET_PROPERTY_DATA_BYID_REQUEST = "GET_PROPERTY_DATA_BYID_REQUEST";
export const GET_PROPERTY_DATA_BYID_SUCCESS = "GET_PROPERTY_DATA_BYID_SUCCESS";
export const GET_PROPERTY_DATA_BYID_FAIL = "GET_PROPERTY_DATA_BYID_FAIL";

export const ADD_IMAGE_GALLERY_REQUEST = "ADD_IMAGE_GALLERY_REQUEST";
export const ADD_IMAGE_GALLERY_SUCCESS = "ADD_IMAGE_GALLERY_SUCCESS";
export const ADD_IMAGE_GALLERY_FAIL = "ADD_IMAGE_GALLERY_FAIL";

export const GET_IMAGES_GALLERY_REQUEST = "GET_IMAGES_GALLERY_REQUEST";
export const GET_IMAGES_GALLERY_SUCCESS = "GET_IMAGES_GALLERY_SUCCESS";
export const GET_IMAGES_GALLERY_FAIL = "GET_IMAGES_GALLERY_FAIL";

export const DELETE_IMAGES_FROM_GALLERY_REQUEST =
  "DELETE_IMAGES_FROM_GALLERY_REQUEST";
export const DELETE_IMAGES_FROM_GALLERY_SUCCESS =
  "DELETE_IMAGES_FROM_GALLERY_SUCCESS";
export const DELETE_IMAGES_FROM_GALLERY_FAIL =
  "DELETE_IMAGES_FROM_GALLERY_FAIL";

export const ADMIN_BLOG_ADD_REQUEST = "ADMIN_BLOG_ADD_REQUEST";
export const ADMIN_BLOG_ADD_SUCCESS = "ADMIN_BLOG_ADD_SUCCESS";
export const ADMIN_BLOG_ADD_FAIL = "ADMIN_BLOG_ADD_FAIL";

export const ADMIN_BLOG_LIST_SHOW_REQUEST = "ADMIN_BLOG_LIST_SHOW_REQUEST";
export const ADMIN_BLOG_LIST_SHOW_SUCCESS = "ADMIN_BLOG_LIST_SHOW_SUCCESS";
export const ADMIN_BLOG_LIST_SHOW_FAIL = "ADMIN_BLOG_LIST_SHOW_FAIL";

export const ADMIN_BLOG_DELETE_REQUEST = "ADMIN_BLOG_DELETE_REQUEST";
export const ADMIN_BLOG_DELETE_SUCCESS = "ADMIN_BLOG_DELETE_SUCCESS";
export const ADMIN_BLOG_DELETE_FAIL = "ADMIN_BLOG_DELETE_FAIL";

export const ADMIN_BLOG_EDIT_REQUEST = "ADMIN_BLOG_EDIT_REQUEST";
export const ADMIN_BLOG_EDIT_SUCCESS = "ADMIN_BLOG_EDIT_SUCCESS";
export const ADMIN_BLOG_EDIT_FAIL = "ADMIN_BLOG_EDIT_FAIL";


export const ADMIN_BLOG_GET_DATA_BYID_REQUEST = "ADMIN_BLOG_GET_DATA_BYID_REQUEST";
export const ADMIN_BLOG_GET_DATA_BYID_SUCCESS = "ADMIN_BLOG_GET_DATA_BYID_SUCCESS";
export const ADMIN_BLOG_GET_DATA_BYID_FAIL = "ADMIN_BLOG_GET_DATA_BYID_FAIL";



export const USER_SEEHIS_FAMILYMEMBER_REQUEST = "USER_SEEHIS_FAMILYMEMBER_REQUEST";
export const USER_SEEHIS_FAMILYMEMBER_SUCCESS = "USER_SEEHIS_FAMILYMEMBER_SUCCESS";
export const USER_SEEHIS_FAMILYMEMBER_FAIL = "USER_SEEHIS_FAMILYMEMBER_FAIL";



