export const ALL_VENDER_LIST_SHOW_TOADMIN_REQUEST =
  "ALL_VENDER_LIST_SHOW_TOADMIN_REQUEST";
export const ALL_VENDER_LIST_SHOW_TOADMIN_SUCCESS =
  "ALL_VENDER_LIST_SHOW_TOADMIN_SUCCESS";
export const ALL_VENDER_LIST_SHOW_TOADMIN_FAIL =
  "ALL_VENDER_LIST_SHOW_TOADMIN_FAIL";

export const VENDER_REGISTER_REQUEST = "VENDER_REGISTER_REQUEST";
export const VENDER_REGISTER_SUCCESS = "VENDER_REGISTER_SUCCESS";
export const VENDER_REGISTER_FAIL = "VENDER_REGISTER_FAIL";

export const VENDER_ADD_PRODUCT_REQUEST = "VENDER_ADD_PRODUCT_REQUEST";
export const VENDER_ADD_PRODUCT_SUCCESS = "VENDER_ADD_PRODUCT_SUCCESS";
export const VENDER_ADD_PRODUCT_FAIL = "VENDER_ADD_PRODUCT_FAIL";

export const VENDER_PRODUCT_LIST_REQUEST = "VENDER_PRODUCT_LIST_REQUEST";
export const VENDER_PRODUCT_LIST_SUCCESS = "VENDER_PRODUCT_LIST_SUCCESS";
export const VENDER_PRODUCT_LIST_FAIL = "VENDER_PRODUCT_LIST_FAIL";

export const VENDER_UPDATE_PRODUCT_REQUEST = "VENDER_UPDATE_PRODUCT_REQUEST";
export const VENDER_UPDATE_PRODUCT_SUCCESS = "VENDER_UPDATE_PRODUCT_SUCCESS";
export const VENDER_UPDATE_PRODUCT_FAIL = "VENDER_UPDATE_PRODUCT_FAIL";

export const VENDER_PRODUCT_GETBYID_REQUEST = "VENDER_PRODUCT_GETBYID_REQUEST";
export const VENDER_PRODUCT_GETBYID_SUCCESS = "VENDER_PRODUCT_GETBYID_SUCCESS";
export const VENDER_PRODUCT_GETBYID_FAIL = "VENDER_PRODUCT_GETBYID_FAIL";

export const VENDER_PRODUCT_DELETE_REQUEST = "VENDER_PRODUCT_DELETE_REQUEST";
export const VENDER_PRODUCT_DELETE_SUCCESS = "VENDER_PRODUCT_DELETE_SUCCESS";
export const VENDER_PRODUCT_DELETE_FAIL = "VENDER_PRODUCT_DELETE_FAIL";

export const VENDER_ADD_NOTES_REQUEST = "VENDER_ADD_NOTES_REQUEST";
export const VENDER_ADD_NOTES_SUCCESS = "VENDER_ADD_NOTES_SUCCESS";
export const VENDER_ADD_NOTES_FAIL = "VENDER_ADD_NOTES_FAIL";

export const VENDER_NOTES_LIST_REQUEST = "VENDER_NOTES_LIST_REQUEST";
export const VENDER_NOTES_LIST_SUCCESS = "VENDER_NOTES_LIST_SUCCESS";
export const VENDER_NOTES_LIST_FAIL = "VENDER_NOTES_LIST_FAIL";

export const VENDER_NOTES_GET_DATA_BYID_REQUEST =
  "VENDER_NOTES_GET_DATA_BYID_REQUEST";
export const VENDER_NOTES_GET_DATA_BYID_SUCCESS =
  "VENDER_NOTES_GET_DATA_BYID_SUCCESS";
export const VENDER_NOTES_GET_DATA_BYID_FAIL =
  "VENDER_NOTES_GET_DATA_BYID_FAIL";

export const VENDER_NOTES_UPDATE_REQUEST = "VENDER_NOTES_UPDATE_REQUEST";
export const VENDER_NOTES_UPDATE_SUCCESS = "VENDER_NOTES_UPDATE_SUCCESS";
export const VENDER_NOTES_UPDATE_FAIL = "VENDER_NOTES_UPDATE_FAIL";

export const VENDER_NOTES_DELETE_REQUEST = "VENDER_NOTES_DELETE_REQUEST";
export const VENDER_NOTES_DELETE_SUCCESS = "VENDER_NOTES_DELETE_SUCCESS";
export const VENDER_NOTES_DELETE_FAIL = "VENDER_NOTES_DELETE_FAIL";

export const USER_HIRE_PARTNER_OR_VENDER_REQUEST =
  "USER_HIRE_PARTNER_OR_VENDER_REQUEST";
export const USER_HIRE_PARTNER_OR_VENDER_SUCCESS =
  "USER_HIRE_PARTNER_OR_VENDER_SUCCESS";
export const USER_HIRE_PARTNER_OR_VENDER_FAIL =
  "USER_HIRE_PARTNER_OR_VENDER_FAIL";

export const USER_HIRED_PARTNER_VENDER_LIST_REQUEST =
  "USER_HIRED_PARTNER_VENDER_LIST_REQUEST";
export const USER_HIRED_PARTNER_VENDER_LIST_SUCCESS =
  "USER_HIRED_PARTNER_VENDER_LIST_SUCCESS";
export const USER_HIRED_PARTNER_VENDER_LIST_FAIL =
  "USER_HIRED_PARTNER_VENDER_LIST_FAIL";

export const USER_REMOVED_HIRED_PARTNER_VENDER_LIST_REQUEST =
  "USER_REMOVED_HIRED_PARTNER_VENDER_LIST_REQUEST";
export const USER_REMOVED_HIRED_PARTNER_VENDER_LIST_SUCCESS =
  "USER_REMOVED_HIRED_PARTNER_VENDER_LIST_SUCCESS";
export const USER_REMOVED_HIRED_PARTNER_VENDER_LIST_FAIL =
  "USER_REMOVED_HIRED_PARTNER_VENDER_LIST_FAIL";

export const USER_ADD_RATING_REQUEST = "USER_ADD_RATING_REQUEST";
export const USER_ADD_RATING_SUCCESS = "USER_ADD_RATING_SUCCESS";
export const USER_ADD_RATING_FAIL = "USER_ADD_RATING_FAIL";

export const GET_ALL_RATING_REQUEST = "GET_ALL_RATING_REQUEST";
export const GET_ALL_RATING_SUCCESS = "GET_ALL_RATING_SUCCESS";
export const GET_ALL_RATING_FAIL = "GET_ALL_RATING_FAIL";

export const CONTRACT_ACCEPT_REJECT_REQUEST = "CONTRACT_ACCEPT_REJECT_REQUEST";
export const CONTRACT_ACCEPT_REJECT_SUCCESS = "CONTRACT_ACCEPT_REJECT_SUCCESS";
export const CONTRACT_ACCEPT_REJECT_FAIL = "CONTRACT_ACCEPT_REJECT_FAIL";

export const END_THE_CONTRACT_REQUEST = "END_THE_CONTRACT_REQUEST";
export const END_THE_CONTRACT_SUCCESS = "END_THE_CONTRACT_SUCCESS";
export const END_THE_CONTRACT_FAIL = "END_THE_CONTRACT_FAIL";


